Ability to save the clinician Expression in mainform
naveenkumarkandasamy/StaffingUI pull request #39
Opened 2020-06-24 15:10 UTC by GowsalyaSG

2020-06-24 21:58 UTC, naveenkumarkandasamy commented
@GowsalyaSG - What is the contect of the story? Did we miss something earlier and doing it now?

2020-06-25 12:49 UTC, aparnaacco879 commented
> @GowsalyaSG - What is the contect of the story? Did we miss something earlier and doing it now?

2020-06-25 12:51 UTC, aparnaacco879 commented
@naveenkumarkandasamy these changes are related to expressions in UI which was pending before.

2020-06-26 09:53 UTC, naveenkumarkandasamy requested changes

2020-06-26 09:53 UTC, naveenkumarkandasamy commented on src/app/autorun/autorun.component.ts
> +    for (let i=0; i < this.clinicianModel.length; i++){
@GowsalyaSG Indentation not good

2020-06-26 09:53 UTC, naveenkumarkandasamy commented on src/app/form/form.component.ts
> +      for (var i = 0; i < this.model.length; i++) {
Indentation

2020-06-26 10:29 UTC, closed without merging